const RAW_BASE='https://raw.githubusercontent.com/foxigaoqian/game-name-radar/main';
const DATA_URL=`${RAW_BASE}/data/candidates.json`;
const REPORT_URL=`${RAW_BASE}/data/latest-report.json`;
const STATUS_KEY='gameRadar.resultStatus.v9';
const LEGACY_STATUS_KEYS=['gameRadar.resultStatus.v8'];
const els={lastUpdated:document.querySelector('#lastUpdated'),verifyStatus:document.querySelector('#verifyStatus'),sourceCount:document.querySelector('#sourceCount'),newCount:document.querySelector('#newCount'),onlineCount:document.querySelector('#onlineCount'),wikiCount:document.querySelector('#wikiCount'),sourceChips:document.querySelector('#sourceChips'),body:document.querySelector('#resultBody'),empty:document.querySelector('#emptyState'),emptyDetail:document.querySelector('#emptyDetail'),search:document.querySelector('#searchInput'),siteType:document.querySelector('#siteTypeFilter'),recommendation:document.querySelector('#recommendationFilter'),time:document.querySelector('#timeFilter'),refresh:document.querySelector('#refreshBtn'),export:document.querySelector('#exportBtn'),toast:document.querySelector('#toast')};
let candidates=[];let report={};let statuses=loadStatuses();
const LABELS={independent:'证据完整·可正式独立站','test-now':'30%测试局·现在就测',page:'稳定需求·适合专题页',watch:'继续观察',reject:'不建议做',pending:'等待验证',error:'验证失败'};
const TYPE_LABELS={online:'在线游戏型',wiki:'Wiki攻略型',pending:'类型待确认'};
const TREND_LABELS={breakout:'Breakout爆发',rising:'明显上涨',strong:'需求较强但未上涨',moderate:'需求中等',weak:'需求较弱',none:'无可见需求',pending:'等待趋势验证',error:'趋势验证失败'};
const FAST_LABELS={pass:'快速层通过',watch:'快速层观察',weak:'快速热度不足',reject:'快速层淘汰',pending:'等待快速验证'};
const TREND_RANK={breakout:6,rising:5,strong:4,moderate:3,weak:2,none:1,pending:0,error:0};
const RECOMMENDATION_RANK={independent:7,'test-now':6,page:5,watch:4,pending:3,reject:2,error:1};
const FRESHNESS_LABELS={new:'新关键词',existing:'历史旧词',unknown:'历史待确认'};
function readStatusStore(key){try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return{}}}
function loadStatuses(){const merged={};for(const key of [...LEGACY_STATUS_KEYS,STATUS_KEY])Object.assign(merged,readStatusStore(key));return merged}
function saveStatuses(){localStorage.setItem(STATUS_KEY,JSON.stringify(statuses))}
function toast(text){els.toast.textContent=text;els.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.remove('show'),2400)}
function fmtDate(value){if(!value)return'—';const d=new Date(value);if(Number.isNaN(d.getTime()))return value;return new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d)}
function ageDays(value){const t=Date.parse(value||'');return Number.isFinite(t)?(Date.now()-t)/86400000:Infinity}
function normalize(value=''){return value.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,' ').trim()}
function statusKey(c){return`name:${String(c.normalizedName||normalize(c.gameName)||c.id||'').trim()}`}
function isIgnored(c){return statuses[statusKey(c)]==='ignored'||statuses[c.id]==='ignored'}
function ignoreCandidate(c){statuses[statusKey(c)]='ignored';if(c.id)statuses[c.id]='ignored';saveStatuses()}
function migrateIgnoredStatuses(){let changed=false;for(const c of candidates){if(statuses[c.id]==='ignored'&&statuses[statusKey(c)]!=='ignored'){statuses[statusKey(c)]='ignored';changed=true}}if(changed)saveStatuses()}
function classification(c){return c.recommendation||c.level||'pending'}
function siteType(c){return c.siteType?.type||'pending'}
function finalScore(c){return Number.isFinite(c.finalScore)?c.finalScore:Number.isFinite(c.score)?c.score:0}
function seoScore(c){return Number.isFinite(c.seo?.score)?c.seo.score:0}
function fastScore(c){return Number.isFinite(c.fast?.score)?c.fast.score:0}
function trendScore(c){return Number.isFinite(c.trend?.score)?c.trend.score:0}
function isFastPassed(c){return c.fast?.classification==='pass'}
function isTrendRising(c){return['rising','breakout'].includes(c.trend?.classification)}
function isPriorityTrendPending(c){return isFastPassed(c)&&['pending','error',undefined].includes(c.trend?.classification)}
function trends(name,days){return`https://trends.google.com/trends/explore?date=${encodeURIComponent(days===7?'now 7-d':'today 1-m')}&geo=US&q=${encodeURIComponent(name)}`}
function serp(c){const query=siteType(c)==='wiki'?`"${c.gameName}" wiki guide walkthrough`:`"${c.gameName}" play online controls`;return`https://www.google.com/search?q=${encodeURIComponent(query)}`}
function domain(name){return`https://www.namecheap.com/domains/registration/results/?domain=${encodeURIComponent(normalize(name).replaceAll(' ',''))}`}
function filtered(){const q=els.search.value.trim().toLowerCase(),typeFilter=els.siteType.value,filter=els.recommendation.value,days=els.time.value==='all'?Infinity:Number(els.time.value);return candidates.filter(c=>{const cls=classification(c),type=siteType(c);if(typeFilter!=='all'&&type!==typeFilter)return false;if(filter==='trend-rising'&&!isTrendRising(c))return false;if(filter==='recommended'&&!['independent','test-now'].includes(cls))return false;if(filter==='fast-pass'&&!isFastPassed(c))return false;if(filter==='trend-pending'&&!isPriorityTrendPending(c))return false;if(!['all','trend-rising','recommended','fast-pass','trend-pending'].includes(filter)&&cls!==filter)return false;if(ageDays(c.firstSeen)>days)return false;if(q&&!c.gameName.toLowerCase().includes(q)&&!(c.sources||[]).some(s=>(s.name||'').toLowerCase().includes(q)))return false;return!isIgnored(c)}).sort((a,b)=>(RECOMMENDATION_RANK[classification(b)]||0)-(RECOMMENDATION_RANK[classification(a)]||0)||(TREND_RANK[b.trend?.classification]||0)-(TREND_RANK[a.trend?.classification]||0)||finalScore(b)-finalScore(a)||fastScore(b)-fastScore(a)||trendScore(b)-trendScore(a)||seoScore(b)-seoScore(a)||Date.parse(b.firstSeen)-Date.parse(a.firstSeen))}
function renderStats(){const active=candidates.filter(c=>!isIgnored(c)),onlineRising=active.filter(c=>siteType(c)==='online'&&isTrendRising(c)).length,wikiRising=active.filter(c=>siteType(c)==='wiki'&&isTrendRising(c)).length,finalCount=active.filter(c=>classification(c)==='independent').length,testCount=active.filter(c=>classification(c)==='test-now').length;els.sourceCount.textContent=String(report.sources?.length||0);els.newCount.textContent=String(report.totalAdded||0);els.onlineCount.textContent=String(onlineRising);els.wikiCount.textContent=String(wikiRising);els.lastUpdated.textContent=report.scannedAt?fmtDate(report.scannedAt):'尚无扫描结果';const yt=report.youtubeEnabled?` · YouTube已验 ${report.youtubeVerified||0}`:' · YouTube未启用';els.verifyStatus.textContent=`SEO通过 ${report.seoPassedCount||0} · 快速通过 ${report.fastPassedCount||0} · Trends已验 ${report.trendValidatedCount||0} · 测试局 ${testCount} · 正式独立站 ${finalCount}${yt}`;if(els.emptyDetail)els.emptyDetail.textContent=(report.trendPendingCount||0)>0?`仍有 ${report.trendPendingCount} 个强候选等待Trends验证。`:'当前筛选下没有符合条件的结果。'}
function renderSources(){const logs=report.sources||[];els.sourceChips.innerHTML='';if(!logs.length){els.sourceChips.innerHTML='<span class="muted">等待后台自动扫描。</span>';return}for(const log of logs){const chip=document.createElement('span');chip.className=`source-chip ${log.ok?'':'error'}`;const name=document.createElement('b');name.textContent=log.sourceName||log.sourceId;const detail=document.createElement('small');detail.textContent=log.ok?`${log.total||0}项 · 新增${log.added||0}`:log.error||'失败';chip.append(name,detail);els.sourceChips.append(chip)}}
function action(label,href){const a=document.createElement('a');a.className='action';a.href=href;a.target='_blank';a.rel='noopener noreferrer';a.textContent=label;return a}
function judgementLabel(text){const span=document.createElement('span');span.textContent=text;return span}
function small(text){const el=document.createElement('small');el.textContent=text;return el}
function renderSeo(c){const seo=c.seo||{},box=document.createElement('div');box.className='judgement';box.append(judgementLabel(`SEO意图分 ${seoScore(c)} · ${seo.intentProfile||siteType(c)}`));for(const text of(seo.reasons||[]).filter(x=>!x.startsWith('适合')&&!x.startsWith('不建议')).slice(0,2))box.append(small(text));if(Number.isFinite(seo.exactGameRatio))box.append(small(`主词游戏 ${Math.round(seo.exactGameRatio*100)}%${seo.exactNonGameRatio>0?` · 非游戏 ${Math.round(seo.exactNonGameRatio*100)}%`:''} · 歧义 ${seo.nameRisk??'—'}`));return box}
function renderFast(c){const fast=c.fast||{},box=document.createElement('div');box.className='judgement';box.append(judgementLabel(`${FAST_LABELS[fast.classification]||'等待快速验证'} · ${fastScore(c)}分 · ${fast.profile||siteType(c)}`));if(siteType(c)==='online')box.append(small(`在线平台 ${fast.onlinePlatformCount||c.siteType?.onlinePlatformCount||0} · Play长尾 ${fast.onlineSuggestionCount||0}`));else if(fast.youtubeEnabled)box.append(small(`YouTube ${fast.youtubeVideos||0}视频 · ${fast.youtubeChannels||0}频道 · ${Number(fast.youtubeViews||0).toLocaleString()}播放`));if(Number.isFinite(fast.sourceAdded24h))box.append(small(`24h新增 ${fast.sourceAdded24h}源 · 48h ${fast.sourceAdded48h||0}源${fast.bestRank?` · 最佳排名 ${fast.bestRank}`:''}`));if((fast.reasons||[])[0])box.append(small(fast.reasons[0]));return box}
function renderTrend(c){const trend=c.trend||{},box=document.createElement('div');box.className='judgement trend-judgement';box.append(judgementLabel(`${TREND_LABELS[trend.classification]||'等待趋势验证'} · ${trendScore(c)}分 · ${trend.queryProfile||'旧模型'}`));if(trend.marketStatus==='global-rising')box.append(small(`全球${TREND_LABELS[trend.globalClassification]||'上涨'}，美国尚未同步`));else if(trend.marketStatus==='us-rising')box.append(small('美国趋势已明显上涨'));if(trend.qualifiedQuery)box.append(small(`辅助词：${trend.qualifiedQuery}`));if(trend.keywordFreshness)box.append(small(`关键词历史：${FRESHNESS_LABELS[trend.keywordFreshness]||trend.keywordFreshness}${trend.entityConflict?' · 可能来自其他实体':''}`));if(Number.isFinite(trend.ratio7))box.append(small(`美国7天≈${trend.anchor||'基准词'}的 ${(trend.ratio7*100).toFixed(1)}% · 动量 ${trend.sevenDay?.momentum??'—'}x`));const signal=(trend.reasons||[]).find(text=>/上涨|Breakout|尖峰|不是新出现|其他实体/.test(text));if(signal)box.append(small(signal));return box}
function renderAdvice(c){const cls=classification(c),type=siteType(c),box=document.createElement('div');box.className='judgement';const typeBadge=document.createElement('span');typeBadge.className=`recommendation ${cls}`;typeBadge.textContent=TYPE_LABELS[type]||TYPE_LABELS.pending;box.append(typeBadge);box.append(small(LABELS[cls]||cls));if(c.siteType?.reasons?.[0])box.append(small(c.siteType.reasons[0]));if(type==='online')box.append(small(c.siteType?.embedStatus==='needs-check'?'浏览器可玩，iframe权限待确认':'浏览器可玩状态待确认'));if(type==='wiki')box.append(small('适合攻略、Wiki、地图、角色与联机教程'));return box}
function render(){renderStats();renderSources();const list=filtered();els.body.textContent='';els.empty.hidden=list.length>0;for(const c of list.slice(0,500)){const cls=classification(c),tr=document.createElement('tr');const scoreTd=document.createElement('td'),score=document.createElement('span');score.className=`score ${cls}`;score.textContent=['pending','error','reject'].includes(cls)?'—':finalScore(c);scoreTd.append(score);const gameTd=document.createElement('td'),title=document.createElement('strong'),url=document.createElement('a'),meta=document.createElement('span');title.className='game-title';title.textContent=c.gameName;url.className='game-url';url.href=c.sources?.[0]?.url||'#';url.target='_blank';url.rel='noopener noreferrer';url.textContent=c.sources?.[0]?.url||'';meta.className='game-meta';meta.textContent=`发现分 ${c.discoveryScore??'—'} · ${c.sources?.length||0}个来源 · ${fmtDate(c.firstSeen)}`;gameTd.append(title,url,meta);const adviceTd=document.createElement('td');adviceTd.append(renderAdvice(c));const seoTd=document.createElement('td');seoTd.append(renderSeo(c));const fastTd=document.createElement('td');fastTd.append(renderFast(c));const trendTd=document.createElement('td');trendTd.append(renderTrend(c));const sourceTd=document.createElement('td'),chips=document.createElement('div');chips.className='chips';for(const s of c.sources||[]){const chip=document.createElement('span');chip.className='chip';chip.textContent=s.name;chips.append(chip)}sourceTd.append(chips);const actions=document.createElement('td'),wrap=document.createElement('div');wrap.className='actions';wrap.append(action('Trends 7天',trends(c.gameName,7)),action('30天',trends(c.gameName,30)),action(siteType(c)==='wiki'?'Wiki SERP':'Play SERP',serp(c)));if(['independent','test-now'].includes(cls))wrap.append(action('域名',domain(c.gameName)));const copy=document.createElement('button');copy.className='action';copy.textContent='复制';copy.onclick=async()=>{await navigator.clipboard.writeText(c.gameName);toast('已复制游戏名')};const ignore=document.createElement('button');ignore.className='action';ignore.textContent='忽略';ignore.onclick=()=>{ignoreCandidate(c);render();toast(`已永久隐藏：${c.gameName}`)};wrap.append(copy,ignore);actions.append(wrap);tr.append(scoreTd,gameTd,adviceTd,seoTd,fastTd,trendTd,sourceTd,actions);els.body.append(tr)}}
async function load(){els.refresh.disabled=true;try{const stamp=Date.now();const[cRes,rRes]=await Promise.all([fetch(`${DATA_URL}?v=${stamp}`,{cache:'no-store'}),fetch(`${REPORT_URL}?v=${stamp}`,{cache:'no-store'})]);if(!cRes.ok)throw new Error('候选数据读取失败');const cJson=await cRes.json();candidates=Array.isArray(cJson)?cJson:cJson.candidates||[];report=rRes.ok?await rRes.json():{};migrateIgnoredStatuses();render()}catch(e){toast(e.message);render()}finally{els.refresh.disabled=false}}
els.search.addEventListener('input',render);els.siteType.addEventListener('change',render);els.recommendation.addEventListener('change',render);els.time.addEventListener('change',render);els.refresh.addEventListener('click',()=>load().then(()=>toast('结果已刷新')));
els.export.addEventListener('click',()=>{const rows=[['Game Name','Site Type','Embed Status','Final Score','Recommendation','SEO Score','Fast Profile','Fast Score','Trend Profile','Trend Class','US 7d vs Anchor','US 30d vs Anchor','Discovery Score','Sources','URL'],...filtered().map(c=>[c.gameName,TYPE_LABELS[siteType(c)],c.siteType?.embedStatus??'',finalScore(c),LABELS[classification(c)]||classification(c),seoScore(c),c.fast?.profile??'',fastScore(c),c.trend?.queryProfile??'',c.trend?.classification??'',c.trend?.ratio7??'',c.trend?.ratio30??'',c.discoveryScore||0,(c.sources||[]).map(s=>s.name).join(' | '),c.sources?.[0]?.url||''])];const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`game-opportunities-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)});
load();setInterval(load,5*60*1000);
